# Generated by Django 5.2.6 on 2025-09-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthBridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='migrant_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Unnamed Migrant', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qr_code_uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(default='Malayalam', max_length=50),
        ),
    ]
