# Generated by Django 6.0 on 2025-12-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthBridge', '0005_medicalrecord_treated_at_medicalrecord_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('public_key_pem', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('authority', 'Authority')], default='migrant', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='HealthBridge.hospital'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='HealthBridge.hospital'),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='HealthBridge.hospital'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='HealthBridge.hospital'),
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vitals', to='HealthBridge.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='HealthBridge.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('treatment', 'Treatment'), ('referral', 'Referral'), ('research', 'Research'), ('audit', 'Audit')], max_length=40)),
                ('expires_at', models.DateTimeField()),
                ('approved_by_patient', models.BooleanField(default=False)),
                ('approved_by_to_hospital', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='HealthBridge.profile')),
                ('from_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents_out', to='HealthBridge.hospital')),
                ('to_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents_in', to='HealthBridge.hospital')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'from_hospital', 'to_hospital'], name='HealthBridg_patient_1b998a_idx')],
            },
        ),
    ]
