# Generated by Django 6.0 on 2025-12-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthBridge', '0006_hospital_remove_doctorprofile_hospital_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='public_key_pem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
