# Generated by Django 6.0 on 2026-05-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthBridge', '0008_rename_migrant_only_profile_patient_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
